name: "Lint PR for conventional commits"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check-commits:
    name: Run commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required to read the commit history
      - uses: wagoid/commitlint-github-action@v5
